services:
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${PORT:-4000}:4000"  # Backend GraphQL API
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-4000}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost}
    volumes:
      - ./logs:/app/logs  # Persist logs
      - frontend-dist:/app/frontend/dist:ro  # Share frontend build with nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/graphql"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend-dist:/usr/share/nginx/html:ro  # Mount frontend static files
    depends_on:
      - portfolio
    restart: unless-stopped
    networks:
      - portfolio-network

volumes:
  frontend-dist:

networks:
  portfolio-network:
    driver: bridge
